version: '3.8'
services:
  frontend:
    image: docusign_preassessment:client
    build: client
    networks:
      application:
        aliases:
          - frontend
  backend:
    image: docusign_preassessment:backend
    build: server
    networks:
      application:
        aliases:
          - backend
    environment:
      HOST: backend
      ACCESS_TOKEN: "$ACCESS_TOKEN"
      ACCOUNT_ID: "$ACCOUNT_ID"

  nginx:
    depends_on: [frontend, backend]
    build: proxy
    networks:
      application:
        aliases:
          - nginx
    image: nginx:1.19
    ports:
      - 80:80

networks:
  application:
